<?php

return [
    'Beginner' => [
        'duration' => '45 Days',
        'projects' => '3 Portfolio Projects Required',
        'focus' => 'Foundational skills, syntax, basic tools, and core industry workflows.',
        'categories' => [
            'Technology & Data' => [
                'Web Ecosystems & Frontend Architecture (HTML, CSS)',
                'Core Python & Computational Logic',
                'Data Foundations & Visual Analytics (Excel/SQL)',
                'UI/UX Design Fundamentals (Figma Basics)',
                'Introduction to Cloud Computing Concepts',
                'Basic Cyber Hygiene & Network Fundamentals',
            ],
            'Business & Management (BBA/MBA)' => [
                'Digital Marketing Basics & SEO Fundamentals',
                'Financial Modeling & Spreadsheet Analytics',
                'B2B Sales Fundamentals & Lead Generation',
                'Startup Business Planning & Lean Canvas',
                'HR Recruitment Basics & ATS Navigation',
                'Social Media Management & Community Building',
            ],
            'Engineering (Mechanical & Civil)' => [
                '2D Digital Prototyping & Drafting (AutoCAD)',
                'Introduction to Manufacturing Materials',
                'Basic Site Surveying & Spatial Planning',
                'Construction Estimation Basics',
                '3D Modeling Fundamentals (SolidWorks)',
                'HVAC Fundamentals & Thermal Basics',
            ],
            'Law & Legal Studies' => [
                'Foundational Legal Research & Writing',
                'Introduction to Corporate Law Structure',
                'Intellectual Property (IP) Basics',
                'Cyber Law & Digital Ethics',
                'Contracts & Drafting 101',
                'Introduction to Legal Tech Tools',
            ],
            'Mass Communication & Media' => [
                'Graphic Design Essentials (Canva/Photoshop)',
                'Copywriting & Digital Content Creation',
                'Video Editing Basics (Premiere/CapCut)',
                'Mobile Journalism (MoJo) & Storytelling',
                'Corporate PR Basics & Press Releases',
                'Audio Production & Podcasting',
            ],
        ],
    ],
    'Intermediate' => [
        'duration' => '75 Days',
        'projects' => '6 Portfolio Projects Required',
        'focus' => 'Industry-level execution, software integration, data-driven strategy, and specialized workflows.',
        'categories' => [
            'Technology & Data' => [
                'Full Stack Web Development (React/Node)',
                'Applied Machine Learning & Data Modeling',
                'Cloud Architecture & Deployment (AWS/Azure)',
                'Ethical Hacking & Penetration Testing',
                'Mobile App Engineering (Flutter/React Native)',
                'IoT & Smart Connected Systems',
            ],
            'Business & Management (BBA/MBA)' => [
                'AI-Driven Marketing Automation (CRM Workflows)',
                'Financial Analytics & Fintech Systems',
                'Supply Chain Optimization & Logistics Data',
                'Agile Project Management (Scrum/Jira)',
                'E-Commerce Strategy & Scaling',
                'Data-Driven HR Analytics',
            ],
            'Engineering (Mechanical & Civil)' => [
                'Finite Element Analysis (FEA) Simulation',
                'Structural Load Analysis (STAAD.Pro)',
                'Building Information Modeling (BIM/Revit)',
                'Robotics & Mechatronics Integration',
                'CNC/CAM Programming & Machining',
                'Highway & Transportation Systems Design',
            ],
            'Law & Legal Studies' => [
                'Mergers & Acquisitions (M&A) Law',
                'Advanced Contract Negotiation & Redlining',
                'Data Privacy Law (GDPR & Global Tech Compliance)',
                'International Arbitration & Dispute Resolution',
                'Startup Funding Legalities (Term Sheets)',
                'E-Discovery & Litigation Support Operations',
            ],
            'Mass Communication & Media' => [
                'Advanced UI/UX & Interactive Prototyping',
                'Data Journalism & Interactive Visualization',
                'Brand Identity & Corporate Strategy',
                'SEO Architecture & Performance Marketing',
                '3D Animation & Motion Graphics',
                'Technical Writing & API Documentation',
            ],
        ],
    ],
    'Advanced' => [
        'duration' => '90 Days',
        'projects' => '9 Portfolio Projects Required',
        'focus' => 'Enterprise architecture, Generative AI integration, leadership, and startup-ready builds.',
        'categories' => [
            'Technology & Data' => [
                'Applied Generative AI & Autonomous Agents',
                'Enterprise DevOps & Kubernetes CI/CD',
                'Decentralized Systems & Smart Contracts (Web3)',
                'Scalable System Design & Big Data Engineering',
                'Advanced SOC Operations & Cyber Warfare',
                'Quantum Computing Concepts & Cryptography',
            ],
            'Business & Management (BBA/MBA)' => [
                'Algorithmic Trading & AI Finance Models',
                'Enterprise SaaS Scaling & Product-Led Growth',
                'Predictive Analytics for Executive Dashboards',
                'Global Business Strategy & M&A Execution',
                'AI in Supply Chain & Predictive Logistics',
                'Advanced AI Product Management',
            ],
            'Engineering (Mechanical & Civil)' => [
                'Generative Design & AI in CAD Architecture',
                'Computational Fluid Dynamics (CFD)',
                'Smart Cities Infrastructure & IoT Integration',
                'Advanced Aerospace & Composite Materials',
                'Autonomous Robotics Systems & Vision',
                'Geotechnical & Earthquake Engineering',
            ],
            'Law & Legal Studies' => [
                'AI & Algorithmic Liability Law',
                'Decentralized Finance (DeFi) & Crypto Law',
                'Space & Satellite Law Operations',
                'Advanced Tech Patents & IP Litigation',
                'Corporate Cyber-Compliance (CISO Legalities)',
                'International Trade & Tech Tariffs',
            ],
            'Mass Communication & Media' => [
                'AI-Generated Media & Prompt Engineering Workflows',
                'AR/VR Experience Design (Spatial Computing)',
                'Growth Hacking & Programmatic Advertising',
                'Crisis Communications & Deepfake Mitigation',
                'Enterprise Digital Transformation Comms',
                'Metaverse Architecture & Digital World Building',
            ],
        ],
    ],
];
